version: "3.8"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: 
      context: ./server
      target: prod
    environment:
      - NODE_ENV=prod
    volumes:
      - /home/node/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    
  front:
    build: 
      context: ./front
      target: preview
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"

volumes:
  db_data: