version: "3.8"

services:
  db:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - "db_data:/data/db"

  server:
    build:
      context: ./server
      target: dev
    command: npm run start:dev
    volumes:
      - ./server:/home/node
      - /home/node/node_modules
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=mongodb://root:password@db:27017/ratflow?authSource=admin
      - JWT_SECRET=secret
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db

  front:
    build:
      context: ./front
      target: dev
    command: npm run dev
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"

volumes:
  db_data:
